set_project("fivem-parser")
set_version("1.1.1")

set_defaultplat("mingw")
set_defaultarchs("x86_64")

add_rules("mode.debug", "mode.release")
set_policy("build.fence", true)
set_languages("c11", "cxx17")
set_warnings("none")

set_runtimes("static")

if is_mode("debug") then
        set_optimize("none")
        set_symbols("debug")
else
        set_optimize("fastest")
end

local ROOT = os.projectdir()
local V_GLFW = ("%s/vendor/glfw"):format(ROOT)
local V_IMGUI = ("%s/vendor/imgui"):format(ROOT)
local V_STB = ("%s/vendor/stb"):format(ROOT)

target("glfw_win")
        set_kind("static")
        set_group("vendor")
        set_toolchains("mingw")
        add_files(("%s/src/*.c|glx_context.c|linux_joystick.c|macos_time.c|posix_module.c|posix_poll.c|posix_thread.c|posix_time.c|wl_init.c|wl_monitor.c|wl_window.c|x11_init.c|x11_monitor.c|x11_window.c|xkb_unicode.c"):format(V_GLFW))
        add_defines("_GLFW_WIN32")
        add_includedirs(("%s/include"):format(V_GLFW), {public = true})
        add_includedirs(("%s/src"):format(V_GLFW))
target_end()

target("imgui_win")
        set_kind("static")
        set_group("vendor")
        set_toolchains("mingw")
        add_files(("%s/*.cpp|imgui_demo.cpp"):format(V_IMGUI))
        add_files(("%s/backends/imgui_impl_glfw.cpp"):format(V_IMGUI), ("%s/backends/imgui_impl_opengl3.cpp"):format(V_IMGUI))
        add_includedirs(V_IMGUI, {public = true})
        add_includedirs(("%s/backends"):format(V_IMGUI), {public = true})
        add_includedirs(("%s/include"):format(V_GLFW))
target_end()

target("Parser_win")
        set_default(true)
        set_kind("binary")
        set_group("app")
        set_toolchains("mingw")
        set_arch("x86_64")
        set_strip("none")
        add_files("*.c", "*.cpp|platform_mac.mm|platform_linux.cpp")
        add_deps("glfw_win", "imgui_win")
        add_includedirs(("%s/include"):format(V_GLFW), V_IMGUI, ("%s/backends"):format(V_IMGUI), V_STB)
        add_ldflags("-mwindows", "-static", "-s", {force = true})
        add_syslinks("opengl32", "gdi32", "user32", "kernel32", "comdlg32", "shell32", "dwmapi")
        set_filename("Parser.exe")
        set_targetdir("$(projectdir)")
        on_run(function (target) end)
target_end()
